### ISSUE TITLE
Samples doesn´t compile in Play 2.0.4

### ISSUE THREAD

**Issue by rock1984** [joscha/play-authenticate#31]
Samples doesn´t compile in Play 2.0.4

[error] C:\workspace\play-authenticate-simple-oauth\app\controllers\Application.java:22: cannot find symbol
[error] symbol  : method noCache(play.mvc.Http.Response)
[error] location: class com.feth.play.module.pa.controllers.Authenticate
[error]                 com.feth.play.module.pa.controllers.Authenticate.noCache(response());
[error]                                                                 ^
[error] 1 error
[error] {file:/C:/workspace/play-authenticate/samples/java/play-authenticate-simple-oauth/}play-authenticate-simple-oauth/compile:compile: javac returned nonzero exit code

[error] C:\workspace\play-authenticate\samples\java\play-authenticate-usage\app\controllers\Account.java:54: cannot find symbol
[error] symbol  : method noCache(play.mvc.Http.Response)
[error] location: class com.feth.play.module.pa.controllers.Authenticate
[error]                 com.feth.play.module.pa.controllers.Authenticate.noCache(response());
[error]                                                                 ^
And in others lines and classes
